package sheets

const (
	VALUE_OPTION_USER_ENTERED            = "USER_ENTERED"
	VALUE_OPTION_RAW                     = "RAW"
	VALUE_OPTION_INPUT_VALUE_UNSPECIFIED = "INPUT_VALUE_OPTION_UNSPECIFIED"
)
